In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [4]:
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

In [7]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [8]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

Train Test Split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

scaling

In [10]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
X_train

array([[-0.54099472, -0.3114864 , -0.57081136, ..., -0.82185632,
        -1.11637606, -0.57539086],
       [ 3.82454561,  1.70296807,  3.95029188, ...,  2.26449118,
        -0.42958127, -0.54584625],
       [ 0.15222101,  0.99085961,  0.09962627, ...,  0.34613104,
        -0.70164491, -0.88821607],
       ...,
       [-0.49516227,  1.84395599, -0.43158575, ...,  0.49766028,
         0.52264147,  2.13228513],
       [-0.52094302,  0.78774143, -0.55465125, ..., -0.75321357,
         0.33186514, -0.09630484],
       [-0.24881288, -0.40946105, -0.30810589, ..., -0.96005098,
        -0.22055676, -0.67850731]])

In [12]:
y_train

96     B
461    M
385    M
484    B
452    B
      ..
131    M
396    B
193    M
490    B
246    B
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [14]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [15]:
y_train

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,

Numpy arrays to PyTorch tensors

In [16]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_test_tensor = torch.from_numpy(y_test)
y_train_tensor = torch.from_numpy(y_train)

In [17]:
X_train_tensor.shape

torch.Size([455, 30])

In [18]:
y_train_tensor.shape

torch.Size([455])

Defining the model

In [22]:
class MySimpleNN():

  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad = True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

Important Parameters

In [20]:
learning_rate = 0.1
epochs = 25

Training Pipeline

In [23]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  #parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 3.718016168746217
Epoch: 2, Loss: 3.5991285139162215
Epoch: 3, Loss: 3.475361222016216
Epoch: 4, Loss: 3.348877075291826
Epoch: 5, Loss: 3.2218036314393257
Epoch: 6, Loss: 3.0918010747503955
Epoch: 7, Loss: 2.954714615547249
Epoch: 8, Loss: 2.8124626242973645
Epoch: 9, Loss: 2.663116507858791
Epoch: 10, Loss: 2.5099929286093796
Epoch: 11, Loss: 2.350370050025603
Epoch: 12, Loss: 2.1874612814184426
Epoch: 13, Loss: 2.028887043529377
Epoch: 14, Loss: 1.8729958161647056
Epoch: 15, Loss: 1.724730439296385
Epoch: 16, Loss: 1.5796030674717978
Epoch: 17, Loss: 1.4408304800495513
Epoch: 18, Loss: 1.3153715464250118
Epoch: 19, Loss: 1.2047178290228706
Epoch: 20, Loss: 1.1100517484545567
Epoch: 21, Loss: 1.032017508562679
Epoch: 22, Loss: 0.9703855102659353
Epoch: 23, Loss: 0.9236727683947787
Epoch: 24, Loss: 0.8891443916518661
Epoch: 25, Loss: 0.8635742989599435


In [24]:
model.bias

tensor([-0.1757], dtype=torch.float64, requires_grad=True)

Evaluation

In [25]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5461680293083191
